<a href="https://colab.research.google.com/github/anupkumar888/Python_Programming/blob/main/1752_assignment1_EDUREKA_ass_1st_SOLUTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and create a real matrix product.

In [ ]:
#Import the numpy library.

import numpy as np

#Create first array A with random ((mxn),m=5,n=3)
A = np.random.random((5,3))
print("First array:")
print(A)

#Create second array B with random((mxn),m=3,a=2).
B = np.random.random((3,2))
print("Second array:")
print(B)

# Find the dot product of arrays A AND B.
C = np.dot(A, B)
print("Dot product of two arrays:")
print(C)

First array:
[[0.14412489 0.79430658 0.3286352 ]
 [0.54541503 0.51740492 0.74682442]
 [0.67822086 0.31423467 0.92842756]
 [0.69707802 0.14453813 0.85441936]
 [0.51074758 0.15624757 0.67570572]]
Second array:
[[0.1010182  0.53470136]
 [0.1845478  0.52080395]
 [0.01564622 0.66432523]]
Dot product of two arrays:
[[0.16628867 0.70906243]
 [0.16226776 1.05723498]
 [0.14103035 1.14307812]
 [0.11046019 1.01561692]
 [0.09100219 0.80336013]]


Problem Statement 2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only. 
Hint: You can use isdigit(),islower(), and isupper() function. 
Example:  

In [ ]:
#Import the numpy library.

import numpy as np

#Create first array A with random strings

Q = np.array(['Python','C++','00', 'PHP', 'JAVASCRIPT', 'STARWAR','99','html5', '5'], dtype=np.str)
print("\nOriginal Array:","\n")
print(Q)

#Check the array A, that there is any numbers/digits. 
A = np.char.isdigit(Q)

#Check the array B, that there is any lower case strings.
B = np.char.islower(Q)

#Check the array C, that there is any upper case strings.
C = np.char.isupper(Q)

# Print the array A,B,C
print("Digits only =", A,"\n")
print("Lower cases only =", B,"\n")
print("Upper cases only =", C,"\n")


Original Array: 

['Python' 'C++' '00' 'PHP' 'JAVASCRIPT' 'STARWAR' '99' 'html5' '5']
Digits only = [False False  True False False False  True False  True] 

Lower cases only = [False False False False False False False  True False] 

Upper cases only = [False  True False  True  True  True False False False] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


In [ ]:
#Import the numpy library.

import numpy as np

#Create first array A with random strings

Q = np.array(['Python','C++','00', 'PHP', 'JAVASCRIPT', 'STARWAR','99','html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(Q,"\n")
#Check the array Q, that there is any numbers/digits using "for" loop. 
for i in Q:
  print(" Is Digit:",i.isdigit())
print("\n")

#Check the array Q, that there is lower case using "for" loop. 
for i in Q:
  print(" Is Lower Case:",i.islower())
print("\n")

#Check the array Q, that there is upper case using "for" loop. 
for i in Q:
  print(" Is Upper Case:",i.isupper())
print("\n","END")


Original Array:
['Python' 'C++' '00' 'PHP' 'JAVASCRIPT' 'STARWAR' '99' 'html5' '5'] 

 Is Digit: False
 Is Digit: False
 Is Digit: True
 Is Digit: False
 Is Digit: False
 Is Digit: False
 Is Digit: True
 Is Digit: False
 Is Digit: True


 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: False
 Is Lower Case: True
 Is Lower Case: False


 Is Upper Case: False
 Is Upper Case: True
 Is Upper Case: False
 Is Upper Case: True
 Is Upper Case: True
 Is Upper Case: True
 Is Upper Case: False
 Is Upper Case: False
 Is Upper Case: False

 END


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and 𝑌 as input and perform the following tasks: 

Tasks to be performed: 

1.Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋 

2.Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌 

3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively 

4.Reshape both the NumPy arrays to (4,4)

5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 - np2) 

6.Print all the elements of np3 in a single dimension list like the format as shown below: 
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [61]:
num =[1,1]
print(*num)

1 1


In [73]:
listQ = [1, 2, 3, 4, 5, 16, 7, 8, 9,10,11,22,13,14,5,16]

# Create a list (lst2) starting at one (1) with 16 elements at a step of  1

lst1= listQ[0:16:1]
print("Lst1=",lst1)



Lst1= [1, 2, 3, 4, 5, 16, 7, 8, 9, 10, 11, 22, 13, 14, 5, 16]


In [78]:
listP = [1, 2, 3, 9, 5, 0, 7, 8, 9,10,11,12,13,8,15,16]

# Create a list (lst2) starting at one (1) with 16 elements at a step of 1

lst2=listP[0:16:1]
print("Lst2=",lst2)


Lst2= [1, 2, 3, 9, 5, 0, 7, 8, 9, 10, 11, 12, 13, 8, 15, 16]


In [79]:
#Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

import numpy as np
np1=np.array(lst1)
print("np1=",np1)

np1= [ 1  2  3  4  5 16  7  8  9 10 11 22 13 14  5 16]


In [125]:
np2=np.array(lst2)
print("np2 =",np2)

np2 = [ 1  2  3  9  5  0  7  8  9 10 11 12 13  8 15 16]


In [126]:
# Reshape both the NumPy arrays to (4,4)
import numpy as np

newarr1 = np1.reshape(4, 4)

print("newarr1=",newarr1)

newarr1= [[ 1  2  3  4]
 [ 5 16  7  8]
 [ 9 10 11 22]
 [13 14  5 16]]


In [127]:
import numpy as np

newarr2 = np2.reshape(4, 4)

print("newarr2=",newarr2)

newarr2= [[ 1  2  3  9]
 [ 5  0  7  8]
 [ 9 10 11 12]
 [13  8 15 16]]


In [129]:
#Create a new np array (np3) with values obtained by subtracting both the arrays (np1 - np2)

np3 =(newarr1-newarr2)            # Since nearr1=np1 and newarr2=np2.
print("np3=",np3)

np3= [[  0   0   0  -5]
 [  0  16   0   0]
 [  0   0   0  10]
 [  0   6 -10   0]]


In [130]:
# Print all the elements of np3 in a single dimension list like the format as shown below: a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]

a = np1.reshape(1,16)

print("a=",a)

a= [[ 1  2  3  4  5 16  7  8  9 10 11 22 13 14  5 16]]


Problem Statement 4: Write a Python program that takes two integer-NumPy arrays,
𝑃 and 𝑄 of shape [3 ∗ 3] and perform the following task: 

Task to be performed:
 
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄)

In [110]:
import numpy as np

P1 = np.arange(1,10)

P = P1.reshape(3,3)
print("P=",P)



P= [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
import numpy as np

Q1 = np.arange(0,9)

Q = Q1.reshape(3,3)
print("Q=",Q)


Q= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [115]:
import numpy as np

#Print difference of (P-Q) in X
X=(P-Q)
print("X=",P-Q)

X= [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [120]:
#Print Q(P-Q) INTO Y
Y=Q*X                       #(SINCE X=(P-Q))
print("Y=",Y)

Y= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [121]:
# Print the value of P-(Q(P-Q)) INTO Z
Z=P-Y                       #(SINCE Y=Q*X)
print("Z=",Z)

Z= [[1 1 1]
 [1 1 1]
 [1 1 1]]
