<a href="https://colab.research.google.com/github/anupkumar888/Python_Programming/blob/Python-programming/1_Introduction_Degree_to_celcious_bclmn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install tensorflow in case of Jupyter/pycharm notebook 
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf
import keras 
print(tf.__version__)

2.9.2


In [3]:
#Set out Training Data

In [4]:
import numpy as np
X=np.array([1,2,3,4,5,6,7])
Y=np.array([3,5,7,9,11,13,15])

** Create Model **

In [5]:
l0=tf.keras.layers.Dense(units=1,input_shape=[1])



Sequential Models

In [6]:
model=tf.keras.Sequential(l0)


In [7]:
model

Compile Model


1. Loss Function
2. optimiser


In [8]:
model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.Adam(0.1))

In [9]:
model.fit(X,Y,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 548ms/step - loss: 43.2125
Epoch 2/50
1/1 [==============================] - 0s 12ms/step - loss: 36.4233
Epoch 3/50
1/1 [==============================] - 0s 10ms/step - loss: 30.2327
Epoch 4/50
1/1 [==============================] - 0s 9ms/step - loss: 24.6487
Epoch 5/50
1/1 [==============================] - 0s 7ms/step - loss: 19.6756
Epoch 6/50
1/1 [==============================] - 0s 9ms/step - loss: 15.3127
Epoch 7/50
1/1 [==============================] - 0s 12ms/step - loss: 11.5537
Epoch 8/50
1/1 [==============================] - 0s 6ms/step - loss: 8.3859
Epoch 9/50
1/1 [==============================] - 0s 12ms/step - loss: 5.7889
Epoch 10/50
1/1 [==============================] - 0s 6ms/step - loss: 3.7345
Epoch 11/50
1/1 [==============================] - 0s 12ms/step - loss: 2.1857
Epoch 12/50
1/1 [==============================] - 0s 7ms/step - loss: 1.0967
Epoch 13/50
1/1 [==============================] - 0s 6ms/s

In [11]:
Y_hat=model.predict([10])

1/1 [==============================] - 0s 30ms/step


In [12]:
Y_hat

array([[20.056105]], dtype=float32)

In [14]:
l0.get_weights()

[array([[1.895619]], dtype=float32), array([1.099914], dtype=float32)]

Model 2

In [ ]:
X=np.array([1,2,3,4,5,6,7])
Y=np.array([3,5,7,9,11,13,15])

l0=tf.keras.layers.Dense(units=4,input_shap=[1])
l1=tf.keras.layers.Dense(units=4)
l2=tf.keras.layers.Dense(units=1)

import tensoflow as tf
model=tf.keras.Sequental([10,11,12])

model.copile(loss="mean_squared_error",optimizer=tf.keras.optimizer.Adam(0.1))

model.fit(X,Y,EPOCHS=50)
y+hat=model.predict([10])
print(y_hat)

In [16]:

X=np.array([1,2,3,4,5,6,7])
Y=np.array([3,5,7,9,11,13,15])

l0=tf.keras.layers.Dense(units=4,input_shape=[1])
l1=tf.keras.layers.Dense(units=4)
l2=tf.keras.layers.Dense(units=1)

import tensorflow as tf
model=tf.keras.Sequential([l0,l1,l2])

model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.Adam(0.1))

model.fit(X,Y,epochs=50)
y_hat=model.predict([10])
print(y_hat)

Epoch 1/50
1/1 [==============================] - 0s 398ms/step - loss: 33.6216
Epoch 2/50
1/1 [==============================] - 0s 7ms/step - loss: 3.5347
Epoch 3/50
1/1 [==============================] - 0s 8ms/step - loss: 18.0246
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 3.6963
Epoch 5/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6099
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 5.6912
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 8.0110
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 5.8115
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 2.0015
Epoch 10/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0164
Epoch 11/50
1/1 [==============================] - 0s 6ms/step - loss: 1.2355
Epoch 12/50
1/1 [==============================] - 0s 6ms/step - loss: 3.4436
Epoch 13/50
1/1 [==============================] - 0s 8ms/step - loss

In [17]:
y_hat

array([[20.822166]], dtype=float32)

In [20]:
l0.get_weights()

[array([[0.05575496, 0.47613376, 1.0287367 , 0.50593096]], dtype=float32),
 array([-0.4755208 , -0.55015093,  0.08566988,  0.10435163], dtype=float32)]

In [21]:
l1.get_weights()


[array([[ 0.02859687,  0.00852909,  0.8356164 , -0.23127457],
        [-0.08875041, -0.88820374, -0.21536902, -0.21804954],
        [-0.7346085 , -0.3089071 ,  0.24249932,  0.70423156],
        [-0.845645  ,  0.8821765 , -0.18475692,  0.8859168 ]],
       dtype=float32),
 array([-0.2525846 , -0.1164773 ,  0.21651036,  0.24670948], dtype=float32)]

In [22]:
l2.get_weights()

[array([[-0.8498501 ],
        [-0.28208604],
        [ 0.13044874],
        [ 0.7968369 ]], dtype=float32), array([0.35981375], dtype=float32)]