<a href="https://colab.research.google.com/github/anupkumar888/Python_Programming/blob/Python-programming/insurance_price_prediction_rm963.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [198]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [199]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"/content/drive/MyDrive/PYTHON PROGRAMMING/Colab Notebooks/Machine Learning/ML REGRESSI0N ASSIGNMENT/insurance_cdmc3.csv")

df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [200]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [201]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [202]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [203]:
df["children"]

0       0
1       1
2       3
3       0
4       0
       ..
1333    3
1334    0
1335    0
1336    0
1337    0
Name: children, Length: 1338, dtype: int64

In [204]:
df["children"].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [205]:
df.loc[df["children"]<3,'children'] = 0

df.loc[df["children"]>=3,'children'] = 1
print (df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         0     no  southeast   1725.55230
2      28    male  33.000         1     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         1     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [206]:
df['children'].value_counts()

0    1138
1     200
Name: children, dtype: int64

In [207]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         0     no  southeast   1725.55230
2   28    male  33.000         1     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [208]:
df_temp=pd.get_dummies(df[["sex","smoker"]])

In [209]:
df_temp.head()

sex_female  sex_male  smoker_no  smoker_yes
0           1         0          0           1
1           0         1          1           0
2           0         1          1           0
3           0         1          1           0
4           0         1          1           0

In [210]:
df_temp.shape

(1338, 4)

In [211]:
df3=pd.concat([df,df_temp],axis=1)

df3.head()

age     sex     bmi  children smoker     region      charges  sex_female  \
0   19  female  27.900         0    yes  southwest  16884.92400           1   
1   18    male  33.770         0     no  southeast   1725.55230           0   
2   28    male  33.000         1     no  southeast   4449.46200           0   
3   33    male  22.705         0     no  northwest  21984.47061           0   
4   32    male  28.880         0     no  northwest   3866.85520           0   

   sex_male  smoker_no  smoker_yes  
0         0          0           1  
1         1          1           0  
2         1          1           0  
3         1          1           0  
4         1          1           0

In [212]:
df3["region"].value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

In [213]:
df3.drop(["sex","smoker","region"],axis=1,inplace=True)

df3

age     bmi  children      charges  sex_female  sex_male  smoker_no  \
0      19  27.900         0  16884.92400           1         0          0   
1      18  33.770         0   1725.55230           0         1          1   
2      28  33.000         1   4449.46200           0         1          1   
3      33  22.705         0  21984.47061           0         1          1   
4      32  28.880         0   3866.85520           0         1          1   
...   ...     ...       ...          ...         ...       ...        ...   
1333   50  30.970         1  10600.54830           0         1          1   
1334   18  31.920         0   2205.98080           1         0          1   
1335   18  36.850         0   1629.83350           1         0          1   
1336   21  25.800         0   2007.94500           1         0          1   
1337   61  29.070         0  29141.36030           1         0          0   

      smoker_yes  
0              1  
1              0  
2              0  
3              0  
4              0  
...          ...  
1333           0  
1334           0  
1335           0  
1336           0  
1337           1  

[1338 rows x 8 columns]

In [214]:
df3.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [215]:
x=df3[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]



In [216]:
y=df3['charges']

In [217]:
x.head()

age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0   19  27.900         0           1         0          0           1
1   18  33.770         0           0         1          1           0
2   28  33.000         1           0         1          1           0
3   33  22.705         0           0         1          1           0
4   32  28.880         0           0         1          1           0

In [218]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [219]:
x=np.asanyarray(x)
y=np.asanyarray(y)

In [220]:
print(x)

[[19.   27.9   0.   ...  0.    0.    1.  ]
 [18.   33.77  0.   ...  1.    1.    0.  ]
 [28.   33.    1.   ...  1.    1.    0.  ]
 ...
 [18.   36.85  0.   ...  0.    1.    0.  ]
 [21.   25.8   0.   ...  0.    1.    0.  ]
 [61.   29.07  0.   ...  0.    0.    1.  ]]


In [221]:
print(y)

[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


In [222]:
import sklearn
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [223]:
x_train

array([[25.   , 26.8  ,  1.   , ...,  1.   ,  1.   ,  0.   ],
       [54.   , 40.565,  1.   , ...,  1.   ,  0.   ,  1.   ],
       [19.   , 20.3  ,  0.   , ...,  1.   ,  1.   ,  0.   ],
       ...,
       [49.   , 41.47 ,  1.   , ...,  0.   ,  1.   ,  0.   ],
       [24.   , 30.21 ,  1.   , ...,  0.   ,  1.   ,  0.   ],
       [29.   , 25.6  ,  1.   , ...,  0.   ,  1.   ,  0.   ]])

In [224]:
y_train

array([ 3906.127  , 48549.17835,  1242.26   , ..., 10977.2063 ,
        4618.0799 ,  5708.867  ])

In [225]:
x_train.shape

(1070, 7)

In [226]:
y_train.shape

(1070,)

In [227]:
x_test.shape

(268, 7)

In [228]:
y_test.shape

(268,)

In [229]:
x_train[0:6]

array([[25.   , 26.8  ,  1.   ,  0.   ,  1.   ,  1.   ,  0.   ],
       [54.   , 40.565,  1.   ,  0.   ,  1.   ,  0.   ,  1.   ],
       [19.   , 20.3  ,  0.   ,  0.   ,  1.   ,  1.   ,  0.   ],
       [56.   , 36.1  ,  1.   ,  0.   ,  1.   ,  1.   ,  0.   ],
       [48.   , 35.625,  1.   ,  0.   ,  1.   ,  1.   ,  0.   ],
       [61.   , 21.09 ,  0.   ,  1.   ,  0.   ,  1.   ,  0.   ]])

In [230]:
from sklearn import linear_model
clf=linear_model.LinearRegression()

In [231]:
print(clf)

LinearRegression()


In [232]:
clf.fit(x_train,y_train)

LinearRegression()

In [233]:
y_pred=clf.predict(x_test)

In [234]:
print(y_pred)

[ 6841.82687163 33133.33886741  8836.85372076  7430.56742924
 12179.24394121 11509.88782077 36735.35843312  4903.82889357
 10847.6022196  13030.01531377 31478.75657652  4194.06490532
  6020.3444276   5706.4306318   3272.23688831  7311.11039775
 34476.81497724 26843.4365698  30285.64865273 11567.60793911
  2670.05652906 10696.40633035 14720.86905603 10925.01971205
  7602.4401091   4330.93746286 14392.10769537  7794.50383808
  1787.88032696  8805.44889123 39899.90550343  4535.16070743
 10445.94651485 18719.6228669   9481.72379589 33608.92947081
  8330.16706911  6021.76853694 11512.0748277  26137.50554969
  3937.02033382  7873.61520686  3855.50596184  3699.96130567
  6612.73511577  2912.48481104 31155.84817681  4059.22025234
 12102.70737831 14709.46559332  8363.64824096  9003.55526345
 26668.76517606  2489.13440753 34218.6324095  12631.17620252
  2795.35069804 12429.623672   10019.22418216 13395.74044009
  -158.32411046  8690.85954859  7175.08082251  8009.22382447
 11642.64030797  8839.13

In [242]:
y_test.shape

(268,)

In [241]:
y_pred.shape

(268,)

In [244]:
# Calculate R2  score to determine the accuracy of model
from sklearn.metrics import r2_score
 r2_score(y_test, y_pred)

0.7416925283514161

***CONCLUSION:***

From the calculated R2 score we can infer that, the regression model is accurate enough and can be used in a Machine Learning Environment.